### ISSUE TITLE
Update pull request action to v.2.2.3

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#11]
Update our [pull request GitHub action](https://github.com/techservicesillinois/splunk-soar-template/blob/main/.github/workflows/pr_reminder.yml) to v2.2.3 to enable direct mentions in chat for pull request reviewers.

## Context

tested the user mapping and it only seems to work if you implement it on a single line with no spaces.  I'll open an issue and see if it could be modified slightly to accept a multiline user mapping
	
also tested the fair recent addition of a ignore-label: no-reminder option which allows a no-reminder tag to be applied to the PR and it will skip notifications.  This could be useful if you have a PR where you don't want notifications

So upgrading your actions to use v2.2.3 seems to work well as long as you have a single line user map (or no user map).  An invalid user map doesn't seem to throw an error and seems to completely break the notification however.

## Tasks

- [ ] update the PR action to the v2.2.3 version or higher
- [ ] update the username mapping to be a single line with no spaces

**Comment by tzturner** [comment]
We are currently waiting to test updates made [here](https://github.com/techservicesillinois/secdev-template-repository/pull/2) via [this PR](https://github.com/techservicesillinois/secdev-template-repository/pull/3).

**Comment by edthedev** [comment]
Checked whether any Teams permissions had changed since last time we set this up - they have not, per latest roadmap notes.

**Comment by edthedev** [comment]
This one works with user mapping:
https://github.com/techservicesillinois/secops-prisma-cspm/blob/main/.github/workflows/reminders.yml

This one works without user mapping:
https://github.com/techservicesillinois/SecOps-Powershell-CSOC/blob/main/.github/workflows/reminders.yml

**Comment by edthedev** [comment]
A new Teams webhook created on 2/6, with version 1.3.0 of the reminder, worked in a non-template repository, as long as a reviewer was added to the pull request.

https://github.com/techservicesillinois/temp-test-secdev-template/actions/runs/4136618450/jobs/7150773020

**Comment by edthedev** [comment]
Works on version 1.3.0 in the template repository as well.

![image](https://user-images.githubusercontent.com/2473032/217886712-e8f7f8d9-d3a5-4079-b0a4-6ceca1f0f788.png)

**Comment by edthedev** [comment]
Version 1.4.0 works.

![image](https://user-images.githubusercontent.com/2473032/217887267-0a361900-debc-488a-be16-67bb1625491c.png)

**Comment by edthedev** [comment]
Version 2.0.0 worked at 11:12 am.

**Comment by edthedev** [comment]
2.1.4. worked at 11:14 am

**Comment by edthedev** [comment]
2.2.3 failed.

**Comment by edthedev** [comment]
2.2.0 failed, and reports failure

(Maybe just a bug release)
```
Run DavideViolante/pr-reviews-reminder-action@v[2](https://github.com/techservicesillinois/secdev-template-repository/actions/runs/4136729080/jobs/7150988349#step:2:2).2.0
  with:
    webhook-url: ***
    provider: msteams
    channel: #general
    github-provider-map: false
  env:
    GITHUB_TOKEN: ***
Getting open pull requests...
Error: axios is not a function
```

**Comment by edthedev** [comment]
2.2.1 fails, with no error message.
(fixes the axios issue, but fails silently as 2.2.3 does)

```
Run DavideViolante/pr-reviews-reminder-action@v2.2.1
Getting open pull requests...
There are 1 open pull requests
There are 1 pull requests waiting for reviews
Notification sent successfully!
```

**Comment by edthedev** [comment]
Version 2.2.1 with a provider map also fails silently.

**Comment by edthedev** [comment]
Version 2.1.4 works with a provider-map, but does not successfully apply the provider-map (known issue in 2.1.4, I believe.)

**Comment by edthedev** [comment]
Version 2.2.1 fails to send a message to Teams, with or without a provider-map.

**Comment by edthedev** [comment]
Double checking secops-prisma-cspm which uses version 2.3.1 using this test pull request: https://github.com/techservicesillinois/secops-prisma-cspm/pull/7

Verified that awscli-login and SecOps-PowerShell-CISDSCTemplates which are still updating the Team channel are both on 1.3.0.

**Comment by edthedev** [comment]
Retested 2.3.1 on the template repo, since that was working for secops-prisma-cspm, but it fails now for the template repo.

**Comment by edthedev** [comment]
Prisma repo reminder works file, with config at:

https://github.com/techservicesillinois/secops-prisma-cspm/blob/bf44644854634e9381cbcf2db3435719ef8897e5/.github/workflows/reminders.yml#L1
